version: 2

# Define the build environment
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"


# Python version and requirements
python:
  install:
    - requirements: docs/requirements.txt

# Specify additional system packages if needed
system_packages:
  - nodejs
  - npm
  - mysql-client

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml
