version: 2

# Define the build environment
build:
  image: latest

# Python version and requirements
python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Specify additional system packages if needed
system_packages:
  - nodejs
  - npm
  - mysql-client

# MkDocs configuration
mkdocs:
  configuration: mkdocs.yml

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Define hooks for before and after build
hooks:
  - trigger: build
    command: echo "Starting build process..."
  - trigger: success
    command: echo "Build completed successfully."
  - trigger: failure
    command: echo "Build failed."



# Define the formats to build
formats:
  - pdf
  - epub


# Submodules configuration
submodules:
  include: all
  recursive: true

# Set the URL for your repository (optional)
repository:
  url: https://github.com/Stefans217/cpd-development
