site_name: CPD Project Documentation
site_description: Documentation for a project built with React (TypeScript) and Node.js with MySQL.
site_author: Stefan Spataro

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Node.js:
      - Getting Started: nodejs/getting-started.md
      - API Reference: nodejs/api-reference.md
  - React (TypeScript):
      - Introduction: react/introduction.md
      - Components: react/components.md
  - MySQL:
      - Setup Guide: mysql/setup.md
      - Queries and Operations: mysql/queries.md

plugins:
  - search